CREATE TABLE Customers (

	Id INT IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(100) NOT NULL,
	LastName NVARCHAR(100) NOT NULL,
	EmailAddress NVARCHAR(100) NOT NULL UNIQUE,
	Password NVARCHAR(200) NOT NULL,
	PhoneNumber NVARCHAR(15) NOT NULL UNIQUE,
	Active BIT DEFAULT 1,
	CreatedOn DATETIME DEFAULT GETDATE(),
	UpdatedOn DATETIME

)